version: "3.8"

services:
  dashboard_app:
    container_name: demo_gtxpro
    restart: always
    build:
      context: ./demo_gtxpro
      dockerfile: Dockerfile
    environment:
      - DASH_ROUTES_PATHNAME_PREFIX=/demo/gtxpro/
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.dashboard_app.loadbalancer.server.port=8050"
      - "traefik.http.routers.dashboard_app.rule=PathPrefix(/demo/gtxpro/)"
    ports:
      - "8050:8050"
